DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS videogames;
DROP TABLE IF EXISTS dishes;

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    make  TEXT NOT NULL,
    color TEXT NOT NULL,
    year INT NOT NULL
);

CREATE TABLE movies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INT NOT NULL,
    director TEXT NOT NULL
);

CREATE TABLE pets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    animal TEXT NOT NULL,
    breed TEXT NOT NULL,
    age INT NOT NULL
);

CREATE TABLE videogames (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INT NOT NULL,
    genre TEXT NOT NULL,
    platform TEXT NOT NULL
);

CREATE TABLE dishes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INT NOT NULL,
    type TEXT NOT NULL,
    vegetarian BOOLEAN NOT NULL
);
