DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS pets;

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    make  TEXT NOT NULL,
    color TEXT NOT NULL,
    year INT NOT NULL
);

CREATE TABLE movies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INT NOT NULL,
    director TEXT NOT NULL
);

CREATE TABLE pets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    animal TEXT NOT NULL,
    breed TEXT NOT NULL,
    age INT NOT NULL
);
