DROP TABLE IF EXISTS cars;

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    make  TEXT NOT NULL,
    color TEXT NOT NULL,
    year INT NOT NULL
)